name: Build and deploy Next.js (Nezox) to Azure Web App - G3CyberspaceWebsite

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: development/using-app-router-with-typescript/nezox

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build

      - name: Zip artifact for deployment
        run: zip -r release.zip .next public package.json next.config.mjs node_modules

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-app
          path: development/using-app-router-with-typescript/nezox/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: nextjs-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'G3CyberspaceWebsite'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_430EE00D71C14B53891E25A4B895FA9B }}
          package: .
